config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # root to: "bikes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :bookings, only: [:new, :create]
  end
  # get 'bikes', to: 'bikes#index'
  get '/profile', to: 'pages#profile'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true
  validates :name, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
    @bikes = Bike.all
    @bike = Bike.new

      # this is for search created by Bahar
      if params[:query].present?
        sql_subquery = <<~SQL
          (bikes.name ILIKE :query OR bikes.description ILIKE :query OR bikes.address ILIKE :query)
          OR
          (bikes.name @@ :query2 OR bikes.description @@ :query2 OR bikes.address @@ :query2)
        SQL
        @bikes = @bikes.joins(:user).where(sql_subquery, query: "%#{params[:query]}%", query2: params[:query])
      else
        @bikes = Bike.all
      end

      if @bikes.empty?
        flash.now[:alert] = "No bikes matching the search criteria were found."
        @latest_bikes = Bike.order(created_at: :desc).limit(6)
      end
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bike: bike})

      }
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new

  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to bikes_path
    else
      render :new
    end
  end

  def delete
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to bikes_path
  end

  def edit
    @bike = Bike.find
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :address, :price, :description, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @bike = Bike.find(params[:bike_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    @booking.user = current_user if current_user

    if @booking.save
      redirect_to bike_path(@bike)
      # alert("Booking was successful!")
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home 
  before_action :authenticate_user!, only: [:profile]


  def home
  end

  def profile
    @user = current_user
    @bikes = @user.bikes
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :photo)
  end

  def bike_params
    params.require(:bike).permit(:name, :price, :description, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<p><%= bike.address %></p>

app/views/bikes/index.html.erb
<div class="container">

  <%# this is for search button created by Bahar%>
  <div class="row justify-content-center mt-4">
    <div class="col-sm-8 my-3">
      <%= form_with url: bikes_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search a bike"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-new-bike" %>
      <% end %>
    </div>
  </div>

  <%# this is all present bikes list %>
  <div class="row position-relative">
    <br>

    <div class="col-8 row">
      <%# this is title for all bikes which searched via user %>
      <div>
        <% if !@bikes.empty? %>
        <% end %>
      </div>

      <% @bikes.each do |bike| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm" style="min-height: 380px;">
            <%= link_to bike_path(bike) do %>
              <% if bike.photo.attached? %>
                <%= cl_image_tag bike.photo.key, class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
              <% else %>
                <%= image_tag 'default_bike.jpg', class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
              <% end %>
            <% end %>
            <div class="card-body" style="min-height: 235px;">
              <% if bike.address.present? %>
                <h3 class="card-title"><%= bike.address.capitalize%></h3>
              <% end %>
              <h5 class="card-title"><%= bike.name.capitalize %></h5>
              <p class="card-text"><strong>Price:</strong> <%= bike.price %> € day</p>
              <p class="card-text overflow-hidden" style="max-height: 30px; min-height: 30px;"><%= bike.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'View', bike_path(bike), class: 'btn btn-new-bike' %>
                </div>

              </div>

            </div>
          </div>
        </div>
      <% end %>
    </div>
      <!-- upload map -------------->
    <% if !@bikes.empty? %>
      <div class="col-4 mb-4 shadow-sm justify-content-center sticky-top" style="height: 600px; position: sticky !important"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <%# -- upload map ------------------------- %>
    <% end %>
  </div>




  <div class="row position-relative">
    <div class="col-8 row">
      <%# this is list of the latest added (if )%>
        <% if @bikes.empty? %>
          <br>

          <%# this is for alert %>
          <div class="row justify-content-center">
            <% if flash[:alert].present? %>
              <div class="alert alert-warning" role="alert">
                <%= flash[:alert] %>
              </div>
            <% end %>
          </div>
          <br>
          <div class="row">
            <%# this is title for other bikes list %>
            <div>
              <h3 class="text-center">No bikes matching the search criteria were found.</h3>
              <h3 class="text-center">Latest added bikes</h3> <br>
            </div>

            <% @latest_bikes.each do |bike| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <%= link_to bike_path(bike) do %>
                    <% if bike.photo.attached? %>
                      <%= cl_image_tag bike.photo.key, class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
                    <% else %>
                      <%= image_tag 'default_bike.jpg', class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
                    <% end %>
                  <% end %>
                  <div class="card-body"  style="min-height: 235px;">
                  <% if bike.address.present? %>
                    <h3 class="card-title"><%= bike.address.capitalize%></h3>
                  <% end %>
                    <h5 class="card-title"><%= bike.name %></h5>
                    <p class="card-text">Price: <%= bike.price %> € day</p>
                    <p class="card-text overflow-hidden" style="max-height: 30px; min-height: 30px;"><%= bike.description %></p>


                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to 'View', bike_path(bike), class: 'btn btn-new-bike' %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

        <% end %>
    </div>
      <!-- upload map -------------->
      <% if @bikes.empty? %>
        <div class="col-4 mb-4 shadow-sm justify-content-center sticky-top" style="height: 600px; position: sticky !important"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      <!-- upload map -------------->
      <% end %>
  </div>



</div>

app/views/bikes/new.html.erb
<div class="container">
  <% if user_signed_in? %>
    <%= form_for @bike, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :photo %>
        <%= f.file_field :photo, class: 'form-control' %>
      </div>
      <%= f.submit 'Save', class: 'btn btn-new-bike' %>
    <% end %>
  <% else %>
    <p>You need to <%= link_to new_user_session_path, class: 'btn btn-new-bike' do %>  before adding a new bike.</p>
       Sign In
    <% end %>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="p-2 m-2 justify-content-center">
  <h1>
    <%= @bike.name.capitalize %> in <%= @bike.address.capitalize if @bike.address.present? %>
  </h1>
</div>

<div class="container d-flex justify-content-center align-items-center row">
  <div class="bike-details card shadow p-3 mb-5 bg-white rounded col-4 p-5 m-5" style="width: 30rem;">
    <div class="d-flex justify-content-center align-items-center">
      <% if @bike.photo.attached? %>
        <%= cl_image_tag @bike.photo.key, class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
      <% else %>
        <%= image_tag 'default_bike.jpg', class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
      <% end %>
    </div>

    <div class="card-body">

      <h5 class="card-title">
        <%= @bike.name.capitalize %> in <%= @bike.address.capitalize if @bike.address.present? %>
      </h5>
      <% if @bike.address.present? %>
        <h3 class="card-title"><%= @bike.address%></h3>
      <% end %>
      <p>price: <%= @bike.price %> € day</p>
      <p class="card-text">description: <%= @bike.description %></p>
      
      <button class="btn-back">
        <%= link_to "Back to list", bikes_path, class: "text-decoration-none text-light"  %>
      </button>
    </div>
  </div>


  <div class="card shadow p-3 mb-5 bg-white rounded col-4">
    <%= simple_form_for [@bike, @booking] do |f|%>
      <%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :end_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
      <%= f.button :submit %>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for [@bike, @booking] do |f|%>
    <%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :end_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
    <%= f.button :submit %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/booking.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h1>This is header</h1>
        <div class="form-control card shadow p-3 mb-5 bg-white rounded" style="width: 400px; height: 500px">
        <p>Start date</p>
        <div>
         <%= simple_form_for [@bike, @booking], data: { insert_in_list_target: "form" } do |f| %>
        <% end %>
</div>
          <input type="submit" name="Book this bike" value="Save" class="btn btn-primary" data-disable-with="Save">
    </div>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= asset_path ("bikecut.png")%>);">
  <div class="containr">
      <h1>BikeBnB</h1>
      <h3>Travel Sustainable</h3>
        <h5>Rent bikes from people or offer your own bike</h5>
      <button class="btn-find-deals">
        <%= link_to "Find deals", bikes_path, class: "text-decoration-none text-light"%>
      </button>
  </div>
</div>

<!-- Illustration inspiration by Dennis de Groot -->

app/views/pages/profile.html.erb
<div class=" container">

  <%# this is title for all bikes which searched via user %>
  <div>
    <h3 class="text-center">My Profile</h3>
    <h4 class="text-center"><%= @user.email %></h4>
  </div>

  <div class="container">
    <h3 class="text-center">My Bikes for Rent</h3>

    <div class="row">
      <% @bikes.each do |bike| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= link_to bike_path(bike) do %>
              <% if bike.photo.attached? %>
                <%= cl_image_tag bike.photo.key, class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
              <% else %>
                <%= image_tag 'default_bike.jpg', class: 'card-img-top', crop: :fill, height: 200, width: 300 %>
              <% end %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= bike.name %></h5>
              <p class="card-text"><strong>Price:</strong> <%= bike.price %> € day</p>
              <p class="card-text overflow-hidden" style="max-height: 30px; min-height: 30px;"><%= bike.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'View', bike_path(bike), class: 'btn btn-new-bike' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-center w-100">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    contact us  <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: 'nav-link active' do %>
      <i class="fa-solid fa-bicycle"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
      </ul>
      <div class="d-flex navbar-right">

        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
            Log Out
          <% end %>



          <%= link_to profile_path, class: 'nav-link active' do %>
            <i class="fa-regular fa-user fa-lg"></i>
          <% end %>


            <%= link_to 'New Bike', new_bike_path, class: 'btn-new-bike' %>
        <% else %>
          <%= link_to new_user_session_path, class: 'btn btn-outline-primary me-2' do %>
            Sign In
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</nav>